/**
 * Written for COMP9024 2013s2 at UNSW Kensington.
 * @author dstacey@cse.unsw.edu.au
 *
 *  DO NOT edit this file
 */

package dracula;

public interface DraculaMove {

   public String getPlayAsString() ;

   public String getMessage();
}
