/**
 * Written for COMP9024 2013s2 at UNSW Kensington.
 * @author dstacey@cse.unsw.edu.au
 *
 *  DO NOT edit this file
 */

package dracula;

import dracula.DraculaMove;

public interface Dracula {

   public DraculaMove decideMove(DraculaView v);

}