/**
 * Written for COMP9024 2013s2 at UNSW Kensington.
 * @author dstacey@cse.unsw.edu.au
 *
 *  DO NOT edit this file
 */

package example;

import example.DraculaMove;

public interface Dracula {

   public DraculaMove decideMove();

}