/**
 * Written for COMP9024 2013s2 at UNSW Kensington.
 * @author dstacey@cse.unsw.edu.au
 *
 *  DO NOT edit this file
 */

package example;

public class DraculaMove {

   private String message;

   public String getMessage() {
      return this.message;
   }

   public String getPlayAsString() {
      //TODO: Implement me
      if (1==1) throw new UnsupportedOperationException("Dracula Move not yet implemented");
      return "";
   }
}
