#define CODE_ALICANTE                "AL"
#define CODE_AMSTERDAM               "AM"
#define CODE_ATHENS                  "AT"
#define CODE_BARCELONA               "BA"
#define CODE_BARI                    "BI"
#define CODE_BELGRADE                "BE"
#define CODE_BERLIN                  "BR"
#define CODE_BORDEAUX                "BO"
#define CODE_BRUSSELS                "BU"
#define CODE_BUCHAREST               "BC"
#define CODE_BUDAPEST                "BD"
#define CODE_CADIZ                   "CA"
#define CODE_CAGLIARI                "CG"
#define CODE_CASTLE_DRACULA          "CD"
#define CODE_CLERMONT_FERRAND        "CF"
#define CODE_COLOGNE                 "CO"
#define CODE_CONSTANTA               "CN"
#define CODE_DUBLIN                  "DU"
#define CODE_EDINBURGH               "ED"
#define CODE_FLORENCE                "FL"
#define CODE_FRANKFURT               "FR"
#define CODE_GALATZ                  "GA"
#define CODE_GALWAY                  "GW"
#define CODE_GENEVA                  "GE"
#define CODE_GENOA                   "GO"
#define CODE_GRANADA                 "GR"
#define CODE_HAMBURG                 "HA"
#define CODE_ST_JOSEPH_AND_ST_MARYS  "JM"
#define CODE_KLAUSENBURG             "KL"
#define CODE_LE_HAVRE                "LE"
#define CODE_LEIPZIG                 "LI"
#define CODE_LISBON                  "LS"
#define CODE_LIVERPOOL               "LV"
#define CODE_LONDON                  "LO"
#define CODE_MADRID                  "MA"
#define CODE_MANCHESTER              "MN"
#define CODE_MARSEILLES              "MR"
#define CODE_MILAN                   "MI"
#define CODE_MUNICH                  "MU"
#define CODE_NANTES                  "NA"
#define CODE_NAPLES                  "NP"
#define CODE_NUREMBURG               "NU"
#define CODE_PARIS                   "PA"
#define CODE_PLYMOUTH                "PL"
#define CODE_PRAGUE                  "PR"
#define CODE_ROME                    "RO"
#define CODE_SALONICA                "SA"
#define CODE_SANTANDER               "SN"
#define CODE_SARAGOSSA               "SR"
#define CODE_SARAJEVO                "SJ"
#define CODE_SOFIA                   "SO"
#define CODE_STRASBOURG              "ST"
#define CODE_SWANSEA                 "SW"
#define CODE_SZEGED                  "SZ"
#define CODE_TOULOUSE                "TO"
#define CODE_VALONA                  "VA"
#define CODE_VARNA                   "VR"
#define CODE_VENICE                  "VE"
#define CODE_VIENNA                  "VI"
#define CODE_ZAGREB                  "ZA"
#define CODE_ZURICH                  "ZU"
#define CODE_NORTH_SEA               "NS"
#define CODE_ENGLISH_CHANNEL         "EC"
#define CODE_IRISH_SEA               "IS"
#define CODE_ATLANTIC_OCEAN          "AO"
#define CODE_BAY_OF_BISCAY           "BB"
#define CODE_MEDITERRANEAN_SEA       "MS"
#define CODE_TYRRHENIAN_SEA          "TS"
#define CODE_IONIAN_SEA              "IO"
#define CODE_ADRIATIC_SEA            "AS"
#define CODE_BLACK_SEA               "BS"
#define CODE_CITY_UNKNOWN            "C?"
#define CODE_SEA_UNKNOWN             "S?"
#define CODE_HIDE                    "HI"
#define CODE_DOUBLE_BACK_1           "D1"
#define CODE_DOUBLE_BACK_2           "D2"
#define CODE_DOUBLE_BACK_3           "D3"
#define CODE_DOUBLE_BACK_4           "D4"
#define CODE_DOUBLE_BACK_5           "D5"
#define CODE_TELEPORT                "TP"

#define ALICANTE                0
#define AMSTERDAM               1
#define ATHENS                  2
#define BARCELONA               3
#define BARI                    4
#define BELGRADE                5
#define BERLIN                  6
#define BORDEAUX                7
#define BRUSSELS                8
#define BUCHAREST               9
#define BUDAPEST                10
#define CADIZ                   11
#define CAGLIARI                12
#define CASTLE_DRACULA          13
#define CLERMONT_FERRAND        14
#define COLOGNE                 15
#define CONSTANTA               16
#define DUBLIN                  17
#define EDINBURGH               18
#define FLORENCE                19
#define FRANKFURT               20
#define GALATZ                  21
#define GALWAY                  22
#define GENEVA                  23
#define GENOA                   24
#define GRANADA                 25
#define HAMBURG                 26
#define ST_JOSEPH_AND_ST_MARYS  27
#define KLAUSENBURG             28
#define LE_HAVRE                29
#define LEIPZIG                 30
#define LISBON                  31
#define LIVERPOOL               32
#define LONDON                  33
#define MADRID                  34
#define MANCHESTER              35
#define MARSEILLES              36
#define MILAN                   37
#define MUNICH                  38
#define NANTES                  39
#define NAPLES                  40
#define NUREMBURG               41
#define PARIS                   42
#define PLYMOUTH                43
#define PRAGUE                  44
#define ROME                    45
#define SALONICA                46
#define SANTANDER               47
#define SARAGOSSA               48
#define SARAJEVO                49
#define SOFIA                   50
#define STRASBOURG              51
#define SWANSEA                 52
#define SZEGED                  53
#define TOULOUSE                54
#define VALONA                  55
#define VARNA                   56
#define VENICE                  57
#define VIENNA                  58
#define ZAGREB                  59
#define ZURICH                  60
#define NORTH_SEA               61
#define ENGLISH_CHANNEL         62
#define IRISH_SEA               63
#define ATLANTIC_OCEAN          64
#define BAY_OF_BISCAY           65
#define MEDITERRANEAN_SEA       66
#define TYRRHENIAN_SEA          67
#define IONIAN_SEA              68
#define ADRIATIC_SEA            69
#define BLACK_SEA               70
#define CITY_UNKNOWN            71
#define SEA_UNKNOWN             72
#define HIDE                    73
#define DOUBLE_BACK_1           74
#define DOUBLE_BACK_2           75
#define DOUBLE_BACK_3           76
#define DOUBLE_BACK_4           77
#define DOUBLE_BACK_5           78
#define TELEPORT                79
#define UNKNOWN_LOCATION        -1
#define NUM_LOCATIONS     80
#define NUM_MAP_LOCATIONS 71